image: php:8.2

before_script:
  - apt-get update -yqq
  - apt-get install -yqq
  - apt install git zip -yqq
  - curl --location --output /usr/local/bin/composer https://getcomposer.org/download/latest-stable/composer.phar
  - chmod +x /usr/local/bin/composer

test:
  script:
    - composer install
    - ./vendor/phpunit/phpunit/phpunit src/tests --bootstrap vendor/autoload.php