version: "3.0"
services:
  apache-example:
    image: edu-sharing/php-auth-plugin:latest
    build:
      context: .
    environment:
      - BASE_URL_INTERNAL=https://repository.8-1.enterprise.134.76.16.75.nip.io/edu-sharing
      - BASE_URL_EXTERNAL=https://repository.8-1.enterprise.134.76.16.75.nip.io/edu-sharing
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/var/www/html/example/data
    ports:
      - "8080:80"