version: "3.0"
services:
  apache-example:
    image: edu-sharing/php-auth-plugin:latest
    build:
      context: .
    environment:
      - BASE_URL_INTERNAL=http://host.docker.internal:8100/edu-sharing
      - BASE_URL_EXTERNAL=http://repository.127.0.0.1.nip.io:8100/edu-sharing
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/var/www/html/example/data
    ports:
      - "8080:80"